### ISSUE TITLE
www.kubevirt.io should redirect to kubevirt.io

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#346]
www or without 'www' should point to kubevirt.io domain, both with https and with http

This should be configured on the DNS registrar or, if using cloudflare or analog, do it there.

**Comment by iranzo** [comment]
Check https://github.com/metal3-io/metal3-io.github.io/issues/58 for some details on how it was done

**Comment by codificat** [comment]
The `www` hostname currently does not resolve:

```
$ host www.kubevirt.io
Host www.kubevirt.io not found: 3(NXDOMAIN)
```

So, rather than an enhancement I believe this is:

/kind bug

I suspect this might be related to the domain transfer.

@fabiand can you confirm that the domain has been moved? Can you add a `CNAME` for `www` that points to `kubevirt.io.`?

We can work on a redirect later if appropriate, but first we need the DNS record to exist.

**Comment by iranzo** [comment]
@fabiand @codificat any news regarding this?

**Comment by ptrnull** [comment]
@fabiand @codificat any news?

**Comment by codificat** [comment]
This has been finally addressed:

```
$ dig +short -t CNAME www.kubevirt.io 
kubevirt.io.
```

/close
