### ISSUE TITLE
lab2: CDI fails to import the fedora image into the PVC

### ISSUE THREAD

**Issue by codificat** [kubevirt/kubevirt.github.io#351]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

In [lab2](https://kubevirt.io/labs/kubernetes/lab2), after creation of the PVC using `pvc_fedora.yml`, the image import process begins but fails to complete.

```
$ kubectl logs -f importer-fedora-4ccb2
I1002 16:29:03.064686       1 importer.go:51] Starting importer
I1002 16:29:03.065695       1 importer.go:107] begin import process
I1002 16:29:05.524499       1 data-processor.go:252] Calculating available size
I1002 16:29:05.538225       1 data-processor.go:260] Checking out file system volume size.
I1002 16:29:05.538852       1 data-processor.go:264] Request image size not empty.
I1002 16:29:05.539173       1 data-processor.go:269] Target size 10Gi.
I1002 16:29:05.673608       1 data-processor.go:182] New phase: Convert
I1002 16:29:05.673757       1 data-processor.go:188] Validating image
I1002 16:29:07.852959       1 qemu.go:212] 0.00
I1002 16:29:16.492692       1 qemu.go:212] 1.00
E1002 16:29:25.532790       1 prlimit.go:164] qemu-img failed output is:
E1002 16:29:25.536946       1 prlimit.go:165]     (0.00/100%)
    (1.00/100%)
qemu-img: curl: The requested URL returned error: 404 Not Found
qemu-img: error while reading sector 280320: Input/output error


E1002 16:29:25.556711       1 data-processor.go:179] exit status 1
[...]
```

**What you expected to happen**:

Image import succeeds.

**Anything else we need to know?**:

This is being reported while testing on minikube, but also hit this recently when testing on a GCP image.

It might be an issue with CDI, didn't have time to investigate more.

Here are the details of the test environment: Kubernetes 1.16, KubeVirt 0.21.0, CDI 1.10.7

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

$ virtctl version
Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl describe deploy -n cdi cdi-operator | grep Image
    Image:      kubevirt/cdi-operator:v1.10.7
```

**Comment by alosadagrande** [comment]
I was able to import Fedora30 image, however I need to apply a few changes to get it run in minikube:

```
$ kubectl logs -f importer-fedora-s5wlk -n lab2
I1004 13:49:50.926621       1 importer.go:51] Starting importer
I1004 13:49:50.927507       1 importer.go:107] begin import process
I1004 13:49:51.919506       1 data-processor.go:252] Calculating available size
I1004 13:49:51.929099       1 data-processor.go:260] Checking out file system volume size.
I1004 13:49:51.929698       1 data-processor.go:264] Request image size not empty.
I1004 13:49:51.930316       1 data-processor.go:269] Target size 4Gi.
I1004 13:49:51.931140       1 data-processor.go:182] New phase: Convert
I1004 13:49:51.931739       1 data-processor.go:188] Validating image
I1004 13:49:53.837429       1 qemu.go:212] 0.00


I1004 13:50:10.048327       1 qemu.go:212] 1.00
I1004 13:50:11.984872       1 qemu.go:212] 2.01
I1004 13:50:15.075642       1 qemu.go:212] 3.01
...
I1004 13:58:39.682660       1 qemu.go:212] 99.75
I1004 13:58:40.767489       1 data-processor.go:182] New phase: Resize
I1004 13:58:40.782123       1 data-processor.go:242] No need to resize image. Requested size: 4Gi, Image size: 4294967296.
I1004 13:58:40.782173       1 data-processor.go:182] New phase: Complete
I1004 13:58:40.782435       1 importer.go:160] Import complete
```

1. First, the qcow2 image is Fedora30 and it is not Fedora 28 as it is showed in the documentation
2. The PVC size will probably cause issues when running on minikube. Since minikube rootfs is running on tmpfs, if we request a PVC of 10G  we will need at least to configure minikube's VM with 12Gi despite of the size of the image. In the following snippet I configured a CirrOS image instead of Fedora with a PVC claim of 10Gi. Take into account that my minikube VM was configured with 8Gi:

```
I1004 12:26:36.101623       1 qemu.go:212] 99.21
I1004 12:26:36.628665       1 data-processor.go:182] New phase: Resize
W1004 12:26:36.678747       1 data-processor.go:239] Available space less than requested size, resizing image to available space 7058563072.
I1004 12:26:36.679068       1 data-processor.go:245] Expanding image size to: 7058563072
```
As you can see the image needed less space than requested however since we requested 10Gi, the image size was expanded to VM's memory limits causing my minikube to start responding.

Below, I modified the pvc_fedora.yaml to requests 4Gi (mininum requirement to run Fedora 30, however in case of CirrOS 2Gi is enough). 
```
  resources:
    requests:
      storage: 4Gi
  storageClassName: hostpath
```
Below the result after importing successfully the image. There was no need to resize since we requested 4Gi and that's what we got.

`I1004 13:58:40.767489       1 data-processor.go:182] New phase: Resize
I1004 13:58:40.782123       1 data-processor.go:242] No need to resize image. Requested size: 4Gi, Image size: 4294967296.
I1004 13:58:40.782173       1 data-processor.go:182] New phase: Complete`

Then, vm could be spinned without issues:

```
$ kubectl get vmi -n lab2
NAME      AGE       PHASE     IP            NODENAME
vm1       28m       Running   172.17.0.16   minikube
```

3. Connection using the virtcl console won't work in minikube since my laptop is not part of the SDN. Therefore we need to expose ssh of the VirtualMachineInstance through nodePort in two steps. First label the VirtualMachine object:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: 2019-10-04T14:06:47Z
  generation: 8
  labels:
    kubevirt.io/os: linux
    **kubevirt.io/vm: vm1**

Finally, I was able to expose the vmi:

virtctl expose vmi vm1  --name=testvm-ssh  --port=20222 --target-port=22  --type=NodePort

Verified:

`ssh root@192.168.122.241 -p 31959
Last login: Fri Oct  4 14:35:26 2019 from 172.17.0.1
[root@vm1 ~]# cat /etc/redhat-release 
Fedora release 30 (Thirty)
[root@vm1 ~]# 
`

I think that this changes must be applied to the documentation and k8s objects.
