### ISSUE TITLE
Would it be beneficial to have a tutorial to get started with KinD

### ISSUE THREAD

**Issue by tylerauerbeck** [kubevirt/kubevirt.github.io#415]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Currently the getting started tutorials include minikube, aws, gcp and katacoda. I've increasingly found myself using [KinD](https://github.com/kubernetes-sigs/kind), so was curious to know whether it would be beneficial to have a guide for KinD as well.

**What you expected to happen**:

Have a guide that walks through getting started with Kubevirt on KinD

**Anything else we need to know?**:
N/A

**Comment by alosadagrande** [comment]
I find KinD really interesting project and getting a lot of traction. However, in my opinion minikube quickstart tutorial covers the basic question: how can I test kubevirt in my laptop or in a local environment. 

I found KinD very tied to docker. At least in my case where I am running Fedora 31, caused me to disable cgroupsv2 since docker CE has no support yet. That's why I run podman. Latest versions of Fedora and probably CentOS has comes with cgroupsv2 enabled by default.

Said that, and taking into account the simplicity to run KinD on Mac, Windows or GNU/Linux I'd suggest to create a blog post that could help KubeVirt community to run VMs on KinD. Since it allows to create multinode cluster configurations, we can show how VM live migration actually works and probably some node affinity/antiaffinity.
