### ISSUE TITLE
Broken virtctl installation script on Mac OS

### ISSUE THREAD

**Issue by zulhfreelancer** [kubevirt/kubevirt.github.io#667]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The `ARCH=$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/') || windows-amd64.exe` in virtctl installation script isn't working for me. It creates "A-Z" file instead.

**My environment**:

* OS: Mac OS 10.12.6
* Chip: Intel (not M1)
* Shell: ZSH/iTerm2

**What you expected to happen**:

I believe the `$ARCH` value should be `darwin-amd64` and shouldn't create any file on current working directory.

Here is the full URL from [v0.36.0 release page](https://github.com/kubevirt/kubevirt/releases/tag/v0.36.0):

https://github.com/kubevirt/kubevirt/releases/download/v0.36.0/virtctl-v0.36.0-darwin-amd64 <-- this

**Anything else we need to know?**:

Webpage URL:

https://kubevirt.io/quickstart_minikube/

File path:

[_includes/quickstarts/virtctl.md](https://github.com/kubevirt/kubevirt.github.io/blob/source/_includes/quickstarts/virtctl.md)

**Comment by mazzystr** [comment]
OSX 10.12.6 (Sierra) is likely to be out of support by Apple's opaque support policy.  

That said I will attempt to assist :
* Since your operating system is so old can you comment with the output from command `uname -a`
* File ./A-Z should not be created.  Please remove this file as it's an indication of a previous bad copy and paste.  
* Please type and run the command manually.  DO NOT COPY AND PASTE.  Run command `ls ./` ensure file ./A-Z does not exist.  Run command `echo "${ARCH}"`.  The `ARCH` environment variable should be equal to `darwin-amd64`
