### ISSUE TITLE
Review use of offensive language

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt.github.io#726]
Review repo for offensive langauge

 * https://github.com/github/renaming
```
git grep -I -E 'master|slave|whitelist|blacklist' -- ':!vendor' ':!cluster-up' ':!cluster-sync' ':!*generated*'
```

**Comment by tylerauerbeck** [comment]
@mazzystr Didn't think I would have the power to reopen, but gave it a shot anyway. This probably needs reopened as there is still some work to do here.

**Comment by cwilkers** [comment]
Searching the actual repo content finds many instances of the potentially offensive language, but mostly in dated blog posts. Rather than try to rewrite so many older posts, we may choose to leave older posts alone, and adopt a new CI check to warn if new content contains words deemed potentially offensive.

**Comment by cwilkers** [comment]
Now working from a new search:

```
git grep -I -E 'master|slave|whitelist|blacklist' -- \
  ':!vendor' ':!cluster-up' ':!cluster-sync' ':!*generated*' ':!*_posts*'
```
