### ISSUE TITLE
Run make targets for each PR

### ISSUE THREAD

**Issue by tylerauerbeck** [kubevirt/kubevirt.github.io#785]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

In https://github.com/kubevirt/kubevirt.github.io/pull/719#discussion_r604195300, it was mentioned that the end goal is to run the following targets for each PR:

- make check_lint
- make check_spelling
- make check_links

Right now (at least from what I can see), it doesn't appear that these are being run as part of the PR process.

**What you expected to happen**:

Automatic process on PR to run desired make targets

**Anything else we need to know?**:

@mazzystr I saw you had mentioned this in some of the closed PR's, so wanted to make sure this didn't get lost in the shuffle. I'm happy to work on this, but wanted to get some insight from you on how you envisioned this being implemented (GitHub actions, prow, etc.)

**Comment by tylerauerbeck** [comment]
@mazzystr @cwilkers I'm going to make an assumption (not having done all that much with Prow before) that this would go here: https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml

Let me know if that makes sense and I can take a look at this (and potentially pull in #716 as well)

**Comment by cwilkers** [comment]
I'll admit ignorance to our CI process, but to my understanding, the kubevirt-github-io-presubmits.yaml you linked to runs rake, which takes its commands from the repo's Rakefile, not Makefile.
Makefiles I understand. Rakefiles not so much.

**Comment by mazzystr** [comment]
Hi, yes we want that but not here.  Take a look at the project-infra repo.
You'll find a presubmits job.  Currently we only have `make check_links` in
the job.  It would be awesome to also have the other check targets.

Rakefile is like Makefile for ruby apps.  The default target does link
checks also.  We need to decouple that since it means we are checking links
twice.

I'm down right now for a bit thanks to @cwilkers having me test a thing
with SELinux.  ;)

Happy to explain more tomorrow.

**Comment by tylerauerbeck** [comment]
@mazzystr No problem. Happy to learn more about this and help add a few things here
