### ISSUE TITLE
Critical network error: Couldn't configure ip nat rules

### ISSUE THREAD

**Issue by crasu** [kubevirt/kubevirt.github.io#845]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I tried to setup kubevirt with minikube by following this tutorial on Ubuntu (https://kubevirt.io/quickstart_minikube/). This results in the VM going into CrashLoopBackOff:
```
#minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
$ minikube start --driver=kvm2  --kubernetes-version='v1.20.2' --cni=flannel  --memory=8gb --cpus=8  
$ export VERSION=v0.51.0 # newer versions fails to start the operator with k8s v1.20.2 but newest k8sversion+newest kubevirt version fails as well
$ kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-cr.yaml
$ kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml
--- wait until everything is up and running ---
$ kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
```

The handler stops the vm immediately and the following error messages show up in the handler log:
```
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of cloudinitdisk volume","name":"testvm","namespace":"default","pos":"vm.go:2215","timestamp":"2022-05-31T16:03:33.110140Z","uid":"c4b5ff00-6881-446c-9d25-a6106538f82a"}
{"component":"virt-handler","level":"error","msg":"virt-launcher crashed due to a network error. Updating VMI testvm status to Failed","pos":"vm.go:1126","timestamp":"2022-05-31T16:03:33.122787Z"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvm","pos":"vm.go:1344","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'eth0': Critical network error: Couldn't configure ip nat rules","timestamp":"2022-05-31T16:03:33.139158Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"testvm","namespace":"default","pos":"vm.go:1553","timestamp":"2022-05-31T16:03:33.143312Z","uid":"c4b5ff00-6881-446c-9d25-a6106538f82a"}

```
**What you expected to happen**:
The vm starts

**Anything else we need to know?**:

> URL where the problem can be found ...
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by shannonmitchell** [comment]
Seeing the exact same thing using minikube v1.26.0 on fedora 26.  I'm running kubevirt v0.55.0 using the minikube addon. Looking through the virt-handler logs showed some issues with the handler finding /var/run/libvirt/libvirt-* & /dev/mem files along with the same network issues you mention.  

Looks like a possible permission issue. It works fine running as root and starting with 'minikube start --force', so that is my current workaround.   It is not ideal though.  Adding the user to the libvirt and kvm groups doesn't seem to help either.

**Comment by maiqueb** [comment]
You're using an unsupported K8s version: v1.20.2

The KubeVirt project only supports the previous 3 kubernetes releases, 1.22 / 1.23 / 1.24.

I recommend you retry with a newer version.

Furthermore, I find suspicious that the error points specifically at configuring IPtables rules - not at creating the tap device  / bridges - which are also privileged operations that occur [before](https://github.com/kubevirt/kubevirt/blob/25b37338917f1a7bfbe3fc07d87672ef1e39389c/pkg/network/infraconfigurators/masquerade.go#L139) attempting to write the NAT rules.

**Comment by crasu** [comment]
At the time it failed with the newest version. Just tried 1.24 fails with the same message.

minikube start --kubernetes-version='v1.24.0' --driver=kvm2 --cni=flannel --memory=8gb --cpus=8

**Comment by lucasgonze** [comment]
What are your thoughts on the IPtables clue, @maiqueb ? What does it imply to you?

**Comment by maiqueb** [comment]
> What are your thoughts on the IPtables clue, @maiqueb ? What does it imply to you?

We've seen issues in the past with nodes having old kernel versions. What is the kernel version of your host ?

I am thinking along the lines of this [opened issue](https://github.com/kubevirt/kubevirt/issues/7006), where iptables (which is [deprecated](https://groups.google.com/g/kubevirt-dev/c/tt61gZtYa-0/m/ngr3kUkeAwAJ) in KubeVirt) was being used instead of nftables - in this issue there's a twist: seems it can't use nftables **nor** iptables, which [throws](https://github.com/kubevirt/kubevirt/blob/25b37338917f1a7bfbe3fc07d87672ef1e39389c/pkg/network/infraconfigurators/masquerade.go#L231) the `Couldn't configure ip nat rules` error.

... having said that, I do not know why iptables / nftables are failing for lack of permissions. 

I'll try to reproduce this when I can spare some time.
